package_submissions:
# these 4 produce RPMs, from the main git repo
  agama: {}
  agama-products: {}
  agama-web-ui: {}
  rubygem-agama-yast: {}
# a RPM, from agama-project/integration-tests
  agama-integration-tests: {}
# also from the main repo, but produces an ISO
  agama-installer:
    gitea_submit:
      source_repo: "https://github.com/agama-project/agama/"
      # TODO:
      # source_ref: ...
      source_run: "make -C live clean sles"
      source_dir: "live/dist"
      target_repo: "gitea@src.suse.de:mvidner/SLES.git"
      target_dir: "agama-installer-SLES"
      target_branch: "fake-16.1"

obs_submissions:
  source_project: "systemsmanagement:Agama:Release"
  target_project: "home:mvidner:FakeFactory"

gitea_submissions:
  source_project: "Devel:YaST:Agama:Release"
  fork_org: mvidner
  target_org: mvidner
  target_branch: fake-slfo-main
